{% set name = "dascore" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dascore-{{ version }}.tar.gz
  sha256: 8bd15626125b16935bf897980419eae314e24e0c28532e1b64b7320aeb012165

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - findiff
    - matplotlib-base
    - pandas
    - pooch >=1.2
    - pydantic >=1.9.0
    - python >=3.9
    - rich
    - scipy
    - setuptools
    - pytables
    - xarray

test:
  imports:
    - dascore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dascore/
  summary: A python library distributed fiber optic sensing
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - d-chambers
